const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, MessageFlags } = require('discord.js');
const e = require('./competitionEngine');
const admin = i => Boolean(i.memberPermissions?.has(PermissionFlagsBits.Administrator));
function build(c){const x=new EmbedBuilder().setColor(c.visual?.color||'#C9A227').setTitle(`${c.metadata?.emoji||'🏆'} ${c.panel?.title||c.metadata?.name||'Competição'}`).setDescription(c.panel?.description||c.metadata?.description||'');if(c.visual?.banner)x.setImage(c.visual.banner);if(c.visual?.thumbnail)x.setThumbnail(c.visual.thumbnail);if(c.visual?.footer)x.setFooter({text:c.visual.footer});return x;}
function rows(c){const defaults=[{emoji:'⚔️',label:'Inscrever-se',action:'register'},{emoji:'📈',label:'Ranking',action:'ranking'},{emoji:'🏟️',label:'Partidas',action:'matches'},{emoji:'📜',label:'Regras',action:'rules'},{emoji:'🏆',label:'Prêmios',action:'rewards'}];const bs=(c.panel?.buttons?.length?c.panel.buttons:defaults).slice(0,25);const out=[];for(let n=0;n<bs.length;n+=5)out.push(new ActionRowBuilder().addComponents(bs.slice(n,n+5).map(b=>new ButtonBuilder().setCustomId(`cmp_public_${c.id}_${b.action}`).setLabel(String(b.label||'Ação').slice(0,80)).setEmoji(b.emoji||'🔘').setStyle(ButtonStyle.Primary))));return out;}
async function handle(i){const parts=i.customId.split('_');const c=e.get(parts[2]),action=parts.slice(3).join('_');if(!c)return i.reply({content:'❌ Competição não encontrada.',flags:MessageFlags.Ephemeral});try{
 if(action==='register'){const p=e.register(c,i.user.id);e.save(c,i.user.id,'register');return i.reply({content:`✅ Inscrição confirmada em **${c.metadata.name}**.`,flags:MessageFlags.Ephemeral});}
 if(action==='ranking'){const rs=e.standings(c);const x=new EmbedBuilder().setColor(c.visual?.color||'#C9A227').setTitle(`📈 ${c.metadata.name} • Ranking`).setDescription(rs.slice(0,25).map(r=>`**${r.rank}.** <@${r.userId}> — **${r.points} pts** • ${r.wins}V ${r.losses}D • saldo ${r.saldo}`).join('\n')||'Nenhum participante.');return i.reply({embeds:[x],flags:MessageFlags.Ephemeral});}
 if(action==='matches'){const ms=c.matches||[];const text=ms.slice(0,20).map(m=>`**${m.id}** • <@${m.participantA}> × <@${m.participantB}> • ${m.status}${m.status==='finished'?` • ${m.scoreA}×${m.scoreB}`:''}`).join('\n')||'Nenhuma partida cadastrada.';return i.reply({embeds:[new EmbedBuilder().setColor(c.visual?.color||'#C9A227').setTitle(`🏟️ ${c.metadata.name} • Partidas`).setDescription(text)],flags:MessageFlags.Ephemeral});}
 if(action==='rules'){const text=(c.rules||[]).map((r,n)=>`**${n+1}. ${r.title||'Regra'}**\n${r.text||r.description||''}`).join('\n\n')||'Nenhuma regra cadastrada.';return i.reply({embeds:[new EmbedBuilder().setColor(c.visual?.color||'#C9A227').setTitle(`📜 ${c.metadata.name} • Regras`).setDescription(text.slice(0,4000))],flags:MessageFlags.Ephemeral});}
 if(action==='rewards'){const text=(c.rewards||[]).map((r,n)=>`**${n+1}. ${r.place||r.position||'Prêmio'}** — ${r.name||r.title||''}${r.value?` • ${r.value}`:''}`).join('\n')||'Nenhuma premiação cadastrada.';return i.reply({embeds:[new EmbedBuilder().setColor(c.visual?.color||'#C9A227').setTitle(`🏆 ${c.metadata.name} • Premiação`).setDescription(text.slice(0,4000))],flags:MessageFlags.Ephemeral});}
 return i.reply({content:'⚙️ Esta ação ainda não possui executor configurado.',flags:MessageFlags.Ephemeral});
}catch(err){const map={ALREADY_REGISTERED:'Você já está inscrito.',FULL:'A competição está lotada.',REGISTRATION_CLOSED:'As inscrições estão fechadas.',COMPETITION_CLOSED:'A competição está encerrada.'};return i.reply({content:`❌ ${map[err.message]||err.message}`,flags:MessageFlags.Ephemeral});}}
module.exports={
 data:new SlashCommandBuilder().setName('competicao-painel').setDescription('📢 Publica o painel público de uma competição').setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName('id').setDescription('ID da competição').setRequired(true).setAutocomplete(true)),
 async autocomplete(i){if(!admin(i))return i.respond([]);const q=(i.options.getString('id')||'').toLowerCase();return i.respond(e.list().filter(c=>`${c.id} ${c.metadata?.name||''}`.toLowerCase().includes(q)).slice(0,25).map(c=>({name:`${c.metadata?.name||'Sem nome'} • ${c.status}`.slice(0,100),value:c.id})));},
 async execute(i){if(!admin(i))return i.reply({content:'❌ Apenas administradores.',flags:MessageFlags.Ephemeral});const c=e.get(i.options.getString('id'));if(!c)return i.reply({content:'❌ Competição não encontrada.',flags:MessageFlags.Ephemeral});const msg=await i.reply({content:'📢 Painel publicado.',embeds:[build(c)],components:rows(c),fetchReply:true});const collector=msg.createMessageComponentCollector({time:7*24*60*60*1000});collector.on('collect',handle);}
};
