/* WORLDWARBR — OLIMPÍADAS DE DUPLAS | independente da Liga */
const fs=require('fs');const path=require('path');const {EmbedBuilder,ActionRowBuilder,StringSelectMenuBuilder,UserSelectMenuBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle,MessageFlags}=require('discord.js');
const FILE=path.join(__dirname,'olimpiadas.json');const CFG=require(FILE);const load=()=>{try{return JSON.parse(fs.readFileSync(FILE,'utf8'));}catch{return {...CFG,duplas:[],resultados:[],ranking:{}}}};const save=d=>fs.writeFileSync(FILE,JSON.stringify(d,null,2),'utf8');const esc=s=>String(s??'').replace(/[\\`*_~|]/g,'');const find=(d,id)=>d.duplas.find(x=>x.id===id);const used=(d,p)=>d.duplas.some(x=>x.pais.toLowerCase()===p.toLowerCase());
// REGISTRO: permitido sempre. CONTABILIZAÇÃO: somente dias pares de setembro.
const canCount=()=>{const d=new Date();return d.getFullYear()===+CFG.ano&&d.getMonth()+1===+CFG.mes&&d.getDate()%2===0};
function rank(d){const r={};for(const j of d.resultados)for(const [id,t] of [[j.ouro,'o'],[j.prata,'p'],[j.bronze,'b']]){r[id]??={vitorias:0,segundo:0,terceiro:0,desempate:0};if(t==='o')r[id].vitorias++;if(t==='p'){r[id].segundo++;r[id].desempate+=3}if(t==='b'){r[id].terceiro++;r[id].desempate++}}return r}
function menuPais(d,id,ph,ex=[]){const usados=new Set(d.duplas.map(x=>x.pais.toLowerCase()));const ps=(CFG.paises||[]).filter(p=>!usados.has(p.toLowerCase())&&!ex.some(e=>e.toLowerCase()===p.toLowerCase()));if(!ps.length)return null;return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(id).setPlaceholder(ph).addOptions(ps.slice(0,25).map(p=>({label:p,value:p}))));}
function panel(d){return new EmbedBuilder().setColor('#D4AF37').setTitle('🟨 OLIMPÍADAS DE DUPLAS').setDescription(`**Vencedores:** <@&1543391902252933170>\n\n**Cada dupla escolherá um País para representar.**\n\n📅 **Contabilização somente nos dias pares de setembro.**\n\n🥇 **Vitória = critério principal**\n🥈 **2º = peso 3 somente no desempate**\n🥉 **3º = peso 1 somente no desempate**\n\n👥 **Duplas:** ${d.duplas.length}\n📊 **Resultados:** ${d.resultados.length}\n⏱️ **Partida:** 1h30min\n\n⚠️ **Apenas DOIS vencedores.**`).setImage(CFG.imagem).setFooter({text:'WorldWarBR • Olimpíadas de Duplas'}).setTimestamp()}
function buttons(){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('olymp_contabilizar').setLabel('Contabilizar').setEmoji('🏅').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('olymp_duplas').setLabel('Ver duplas').setEmoji('👥').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('olymp_registrar').setLabel('Registrar dupla').setEmoji('📝').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('olymp_ranking').setLabel('Ranking').setEmoji('🏆').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('olymp_guia').setLabel('Guia').setEmoji('📖').setStyle(ButtonStyle.Secondary))}
async function painel(i){const c=await i.client.channels.fetch(CFG.canalPainel).catch(()=>null);if(!c?.isTextBased())return i.reply({content:'❌ Canal do painel não encontrado.',flags:MessageFlags.Ephemeral});await c.send({embeds:[panel(load())],components:[buttons()]});return i.reply({content:`✅ Painel das Olimpíadas publicado em <#${CFG.canalPainel}>.`,flags:MessageFlags.Ephemeral})}
// REGISTRO pode ser feito em qualquer dia.
async function registrar(i){return i.reply({content:'📝 **JOGADOR 1**\nSelecione o primeiro integrante.',components:[new ActionRowBuilder().addComponents(new UserSelectMenuBuilder().setCustomId('olymp_reg_p1').setPlaceholder('Selecione o jogador 1'))],flags:MessageFlags.Ephemeral})}
async function regP1(i){return i.update({content:'📝 **JOGADOR 2**\nSelecione o segundo integrante.',components:[new ActionRowBuilder().addComponents(new UserSelectMenuBuilder().setCustomId(`olymp_reg_p2_${i.values[0]}`).setPlaceholder('Selecione o jogador 2'))]})}
async function regP2(i){const p1=i.customId.slice('olymp_reg_p2_'.length),p2=i.values[0],d=load();if(p1===p2)return i.reply({content:'❌ Os jogadores precisam ser diferentes.',flags:MessageFlags.Ephemeral});const old=d.duplas.find(x=>[x.jogador1,x.jogador2].includes(p1)||[x.jogador1,x.jogador2].includes(p2));if(old)return i.reply({content:`❌ Um jogador já pertence à dupla **${esc(old.nome)}**.`,flags:MessageFlags.Ephemeral});const m=menuPais(d,`olymp_reg_pais_${p1}_${p2}`,'Escolha o país');if(!m)return i.reply({content:'❌ Todos os países estão ocupados.',flags:MessageFlags.Ephemeral});return i.update({content:'🌎 **PAÍS**\nPaíses já ocupados não aparecem.',components:[m]})}
async function regPais(i){const q=i.customId.split('_');const p1=q[3],p2=q[4],pais=i.values[0];const m=new ModalBuilder().setCustomId(`olymp_reg_nome_${p1}_${p2}_${encodeURIComponent(pais)}`).setTitle('Nome da dupla');m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('nome').setLabel('Nome da dupla').setPlaceholder('Ex.: Os Imperadores').setStyle(TextInputStyle.Short).setMinLength(2).setMaxLength(40).setRequired(true)));return i.showModal(m)}
async function regNome(i){const q=i.customId.split('_'),p1=q[3],p2=q[4],pais=decodeURIComponent(q.slice(5).join('_')),nome=i.fields.getTextInputValue('nome').trim();const d=load();if(used(d,pais)||d.duplas.some(x=>[x.jogador1,x.jogador2].includes(p1)||[x.jogador1,x.jogador2].includes(p2)))return i.reply({content:'❌ País ou jogador já está ocupado.',flags:MessageFlags.Ephemeral});d.duplas.push({id:`dupla_${Date.now()}_${p1}`,nome,pais,jogador1:p1,jogador2:p2,criadoPor:i.user.id,criadoEm:new Date().toISOString(),ativa:true});d.ranking=rank(d);save(d);const c=await i.client.channels.fetch(CFG.canalTeg).catch(()=>null);if(c?.isTextBased())await c.send({content:'🟨 **OLIMPÍADAS DE DUPLAS — NOVA INSCRIÇÃO**',embeds:[new EmbedBuilder().setColor('#D4AF37').setTitle('📝 NOVA DUPLA REGISTRADA').setDescription(`**${esc(nome)}**\n🌎 ${esc(pais)}\n👥 <@${p1}> + <@${p2}>`)]});return i.reply({content:`✅ Dupla **${esc(nome)}** registrada!`,flags:MessageFlags.Ephemeral})}
async function contabilizar(i){if(!canCount())return i.reply({content:'🚫 **A contabilização só pode ser feita nos dias pares de setembro de 2026.**\n\nO registro de duplas continua disponível normalmente.',flags:MessageFlags.Ephemeral});const d=load();if(d.duplas.length<3)return i.reply({content:'❌ É necessário ter pelo menos 3 duplas.',flags:MessageFlags.Ephemeral});const m=menuPais(d,'olymp_result_ouro','🥇 País vencedor');return i.reply({content:'🏅 **CONTABILIZAÇÃO**\nEscolha 🥇, 🥈 e 🥉.\n📸 Ao final você deverá **ANEXAR o print**. Link não é aceito.',components:[m],flags:MessageFlags.Ephemeral})}
async function ouro(i){const p=i.values[0],m=menuPais(load(),`olymp_result_prata_${encodeURIComponent(p)}`,'🥈 País em 2º',[p]);return i.update({content:`🥇 **${esc(p)}**\nSelecione o 🥈 2º lugar.`,components:[m]})}
async function prata(i){const ouro=decodeURIComponent(i.customId.split('_').slice(3).join('_')),p=i.values[0],m=menuPais(load(),`olymp_result_bronze_${encodeURIComponent(ouro)}_${encodeURIComponent(p)}`,'🥉 País em 3º',[ouro,p]);return i.update({content:`🥇 **${esc(ouro)}**\n🥈 **${esc(p)}**\nSelecione o 🥉 3º lugar.`,components:[m]})}
async function bronze(i){if(!canCount())return i.reply({content:'🚫 A contabilização só pode ser feita nos dias pares de setembro de 2026.',flags:MessageFlags.Ephemeral});const q=i.customId.split('_').slice(3),ouro=decodeURIComponent(q[0]),prata=decodeURIComponent(q[1]),bronze=i.values[0];await i.reply({content:`📸 **ANEXE AGORA O PRINT DA VITÓRIA**\n\n🥇 ${esc(ouro)}\n🥈 ${esc(prata)}\n🥉 ${esc(bronze)}\n\n⚠️ **Somente imagem anexada. Links não são aceitos.**\n⏳ Você tem 2 minutos.`,flags:MessageFlags.Ephemeral});const col=i.channel.createMessageCollector({filter:m=>m.author.id===i.user.id&&m.attachments.size>0,time:120000,max:1});col.on('collect',async msg=>{const a=msg.attachments.find(x=>(x.contentType||'').toLowerCase().startsWith('image/')||/\.(png|jpe?g|webp)$/i.test(x.name||''));if(!a){await msg.reply('❌ Anexe uma imagem **PNG, JPG, JPEG ou WEBP**. Links não são aceitos.').catch(()=>{});col.stop('bad');return}await finalizar(i,ouro,prata,bronze,a)});col.on('end',(_,reason)=>{if(reason==='time')i.followUp({content:'⌛ Tempo esgotado. Contabilização cancelada.',flags:MessageFlags.Ephemeral}).catch(()=>{})})}
async function finalizar(i,ouro,prata,bronze,anexo){const d=load(),a=d.duplas.find(x=>x.pais===ouro),b=d.duplas.find(x=>x.pais===prata),c=d.duplas.find(x=>x.pais===bronze);if(!a||!b||!c)return i.followUp({content:'❌ Dupla não encontrada.',flags:MessageFlags.Ephemeral});d.resultados.push({id:`resultado_${Date.now()}`,data:new Date().toISOString(),ouro:a.id,prata:b.id,bronze:c.id,print:anexo.url,printNome:anexo.name,printTipo:anexo.contentType,registradoPor:i.user.id});d.ranking=rank(d);save(d);const canal=await i.client.channels.fetch(CFG.canalResultados).catch(()=>null);if(canal?.isTextBased())await canal.send({embeds:[new EmbedBuilder().setColor('#D4AF37').setTitle('🏅 RESULTADO — OLIMPÍADAS DE DUPLAS').setDescription(`🥇 **${esc(a.pais)}** — ${esc(a.nome)}\n🥈 **${esc(b.pais)}** — ${esc(b.nome)}\n🥉 **${esc(c.pais)}** — ${esc(c.nome)}\n\n🏆 Vitória = critério principal\n⚖️ Prata = peso 3 no desempate\n⚖️ Bronze = peso 1 no desempate`).setImage(anexo.url).setTimestamp()]});return i.followUp({content:'✅ Resultado contabilizado!\n📸 Print anexado e publicado.\n💾 Ranking atualizado.',flags:MessageFlags.Ephemeral})}
async function duplas(i){const d=load();const t=d.duplas.map((x,n)=>`**${n+1}. ${esc(x.nome)}** — 🌎 ${esc(x.pais)}\n👥 <@${x.jogador1}> + <@${x.jogador2}>`).join('\n\n')||'Nenhuma dupla registrada.';return i.reply({embeds:[new EmbedBuilder().setColor('#D4AF37').setTitle('👥 DUPLAS DAS OLIMPÍADAS').setDescription(t.slice(0,4000))],flags:MessageFlags.Ephemeral})}
async function rankingPainel(i){const d=load(),r=rank(d),l=Object.entries(r).map(([id,v])=>({d:find(d,id),...v})).filter(x=>x.d).sort((a,b)=>b.vitorias-a.vitorias||b.desempate-a.desempate);const t=l.map((x,n)=>`**${n+1}. ${esc(x.d.pais)} — ${esc(x.d.nome)}**\n🥇 ${x.vitorias} • 🥈 ${x.segundo} • 🥉 ${x.terceiro} • ⚖️ ${x.desempate}`).join('\n\n')||'Ainda não há resultados.';return i.reply({embeds:[new EmbedBuilder().setColor('#D4AF37').setTitle('🏆 RANKING — OLIMPÍADAS').setDescription(t.slice(0,4000))],flags:MessageFlags.Ephemeral})}
async function guia(i){const texto=`# 🟨 Olimpíadas de Duplas:\n\n**Vencedores: <@&1543391902252933170>\nCada dupla escolherá um País para representar\nTodos os dias pares do Mês de Setembro!**\n\n#️⃣ **Ranking de países por quantidade de medalhas**\n#️⃣ **Ranking de competidores por quantidade de medalhas**\n**Dupla vencedora:** 🥇\n**Critérios de desempate (apenas para os vivos):\nDupla vice:** 🥈 **(peso: 3)\nDupla lanterna:** 🥉 **(peso: 1)**\n\n***1h30min de partida***\n🚫 **Regras:**\n\n1️⃣ **Em caso de Briga, é possível a troca entre países com as medalhas individuais mantidas.**\n\n2️⃣ **Em caso de Ausência, é possível a substituição DEFINITIVA de um parceiro para outro. As medalhas do País serão mantidas intactas.**\n\n3️⃣ **Em caso de Anti-jogo, será tratado como qualquer outra partida do servidor.**\n\n4️⃣ **Em caso de disputa por um país, será feito um sorteio.**\n\n⚠️ **As Olímpiadas terão apenas DOIS vencedores!**`;return i.reply({embeds:[new EmbedBuilder().setColor('#D4AF37').setTitle('📖 GUIA — OLIMPÍADAS DE DUPLAS').setDescription(texto)],flags:MessageFlags.Ephemeral})}
async function handle(i){const id=i.customId||'';if(id==='olymp_contabilizar')return contabilizar(i);if(id==='olymp_duplas')return duplas(i);if(id==='olymp_registrar')return registrar(i);if(id==='olymp_ranking')return rankingPainel(i);if(id==='olymp_guia')return guia(i);if(id==='olymp_reg_p1')return regP1(i);if(id.startsWith('olymp_reg_p2_'))return regP2(i);if(id.startsWith('olymp_reg_pais_'))return regPais(i);if(id==='olymp_result_ouro')return ouro(i);if(id.startsWith('olymp_result_prata_'))return prata(i);if(id.startsWith('olymp_result_bronze_'))return bronze(i);if(i.isModalSubmit()&&id.startsWith('olymp_reg_nome_'))return regNome(i)}module.exports={painel,handle};